---
- hosts: elevate
  vars:
    project_path: /opt/frontend/shikshagrah
    root_path: /opt/frontend
  tasks:
    - name: Slurp host file
      slurp:
        src: "/opt/backend/deployment/.token"
      register: slurpfile
    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}shikshagrah-portal' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{root_path}}/data2.json'"
      register: vaultCurl
    - name: Change directory
      shell: cd {{project_path}}
    - name: Fetch the latest code
      git:
        repo: https://github.com/vishwanath1004/shikshagrah
        dest: "{{project_path}}"
        version: "{{gitBranch}}"
        force: yes
    - name: Update npm
      shell: cd {{project_path}} && npm i --force
    - name: Set permission
      shell: chmod 744 {{ project_path }}/apps/scripts/json2env.sh
    - name: Generate .env
      shell: cat {{root_path}}/data2.json | jq '.data' > {{ project_path }}/.env && sed -i '1s/^/export const environment = \n/' {{ project_path }}/.env
      register: envConfig
    - debug: msg=" cred {{ envConfig }} "
    - name: Change directory
      shell: chdir {{project_path}}
    - name: Fetch pm2 config file
      shell: "curl --location --request GET '{{ vaultAddress }}shikshagrahportalPm2Config' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data.data' > '{{ project_path }}/pm2.config.json'"
      register: pm2
    - name: Change directory
      shell: cd {{project_path}}
    - name: Remove www folder
      shell: rm -rf www
    # - name: Build pwa app
    #   shell: cd {{project_path}} && pm2 delete shikshagraha-app
    - name: Start pm2
      shell: cd {{project_path}} && pm2 start "npx nx dev shikshagraha-app --port=8000 --verbose" --name shikshagraha-app
